# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  install:
    # Install Sphinx and theme first
    - requirements: docs/requirements.txt
    # Install yapCAD package itself for autodoc/apidoc to generate API documentation
    # This is critical for generating submodule documentation from docstrings
    - method: pip
      path: .

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

submodules:
  include: all
  recursive: true
