/**
 * YapCADViewer - Three.js-based 3D viewer for yapCAD geometry.
 * 
 * Generated by qwen3-coder:30b, reviewed and integrated by Jarvis.
 */

import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { createLightsFromPreset, getPreset } from './lighting';

export interface GeometryEntity {
  id: string;
  name?: string;
  vertices: Float32Array;
  normals?: Float32Array;
  indices?: Uint32Array;
  material?: string;
  layer?: string;
}

export interface ViewerOptions {
  container: HTMLElement;
  antialias?: boolean;
  pixelRatio?: number;
  orthographic?: boolean;
}

export class YapCADViewer {
  private scene: THREE.Scene;
  private camera: THREE.Camera;
  private renderer: THREE.WebGLRenderer;
  private controls: OrbitControls;
  private isOrthographic: boolean;
  private renderId: number | null = null;
  private meshes: THREE.Mesh[] = [];
  private materials: Map<string, THREE.MeshStandardMaterial> = new Map();
  private lights: THREE.Light[] = [];
  private currentLightingPreset: string = 'studio';
  private currentRenderMode: string = 'solid';
  private originalMaterials: Map<THREE.Mesh, THREE.Material | THREE.Material[]> = new Map();
  private wireframeMeshes: Map<THREE.Mesh, THREE.Mesh> = new Map();
  private clippingPlaneMap: Map<string, THREE.Plane> = new Map(); // keyed by 'x','y','z'
  private boundingBox: THREE.Box3 = new THREE.Box3();
  private resizeObserver: ResizeObserver | null = null;
  private scaleGroup: THREE.Group = new THREE.Group();
  private showGrid: boolean = true;

  constructor(private options: ViewerOptions) {
    // Scene
    this.scene = new THREE.Scene();
    this.scene.background = new THREE.Color(0x1a1a2e);

    // Camera
    this.isOrthographic = options.orthographic ?? false;
    const width = options.container.clientWidth || 100;
    const height = options.container.clientHeight || 100;
    const aspect = width / height;
    
    if (this.isOrthographic) {
      const frustumSize = 200;
      this.camera = new THREE.OrthographicCamera(
        (-frustumSize * aspect) / 2, (frustumSize * aspect) / 2,
        frustumSize / 2, -frustumSize / 2,
        0.1, 10000
      );
      this.camera.position.set(0, 0, 100);
    } else {
      this.camera = new THREE.PerspectiveCamera(50, aspect, 0.1, 10000);
      this.camera.position.set(0, 0, 100);
    }

    // Renderer
    this.renderer = new THREE.WebGLRenderer({
      antialias: options.antialias ?? true,
    });
    this.renderer.setSize(options.container.clientWidth, options.container.clientHeight);
    this.renderer.setPixelRatio(options.pixelRatio ?? window.devicePixelRatio);
    this.renderer.localClippingEnabled = true;
    options.container.appendChild(this.renderer.domElement);

    // Controls
    this.controls = new OrbitControls(this.camera, this.renderer.domElement);
    this.controls.enableDamping = true;
    this.controls.dampingFactor = 0.05;

    // Setup
    this.setupLights();
    this.setupMaterialPresets();
    this.setupResizeHandler();
    this.createScaleGrid();
    this.scene.add(this.scaleGroup);
  }

  private setupLights(): void {
    // Initialize with studio lighting preset
    this.setLightingPreset('studio');
  }

  private setupMaterialPresets(): void {
    const presets: Record<string, { color: number; metalness: number; roughness: number }> = {
      brass: { color: 0xb5a642, metalness: 0.8, roughness: 0.3 },
      steel: { color: 0x8090a0, metalness: 0.9, roughness: 0.4 },
      aluminum: { color: 0xd0d5dd, metalness: 0.7, roughness: 0.5 },
      copper: { color: 0xb87333, metalness: 0.85, roughness: 0.35 },
      plastic_white: { color: 0xf0f0f0, metalness: 0.0, roughness: 0.6 },
      plastic_black: { color: 0x202020, metalness: 0.0, roughness: 0.6 },
      plastic_red: { color: 0xcc3333, metalness: 0.0, roughness: 0.6 },
      plastic_blue: { color: 0x3366cc, metalness: 0.0, roughness: 0.6 },
      plastic_green: { color: 0x33cc66, metalness: 0.0, roughness: 0.6 },
      default: { color: 0x99bbdd, metalness: 0.2, roughness: 0.4 },
    };

    for (const [name, props] of Object.entries(presets)) {
      this.materials.set(name, new THREE.MeshStandardMaterial({
        color: props.color,
        metalness: props.metalness,
        roughness: props.roughness,
        side: THREE.DoubleSide,
      }));
    }
  }

  private setupResizeHandler(): void {
    const onResize = () => {
      const { clientWidth, clientHeight } = this.options.container;
      if (clientWidth === 0 || clientHeight === 0) return;
      
      if (this.isOrthographic) {
        const aspect = clientWidth / clientHeight;
        const frustumSize = 200;
        (this.camera as THREE.OrthographicCamera).left = (-frustumSize * aspect) / 2;
        (this.camera as THREE.OrthographicCamera).right = (frustumSize * aspect) / 2;
        (this.camera as THREE.OrthographicCamera).top = frustumSize / 2;
        (this.camera as THREE.OrthographicCamera).bottom = -frustumSize / 2;
      } else {
        (this.camera as THREE.PerspectiveCamera).aspect = clientWidth / clientHeight;
      }
      
      (this.camera as THREE.PerspectiveCamera | THREE.OrthographicCamera).updateProjectionMatrix();
      this.renderer.setSize(clientWidth, clientHeight);
    };

    // Use ResizeObserver for container-level resize (panel drag, etc.)
    if (typeof ResizeObserver !== 'undefined') {
      this.resizeObserver = new ResizeObserver(onResize);
      this.resizeObserver.observe(this.options.container);
    }
    // Fallback to window resize
    window.addEventListener('resize', onResize);
  }

  private createScaleGrid(): void {
    // Clear existing grid
    this.scaleGroup.clear();

    // Grid helper (500mm size, 10 divisions = 50mm grid squares)
    const gridHelper = new THREE.GridHelper(500, 10, 0x444466, 0x333344);
    gridHelper.name = 'grid';
    this.scaleGroup.add(gridHelper);

    // Scale bar - 100mm line from origin to (100,0,0)
    const scaleGeometry = new THREE.BufferGeometry();
    const scaleVertices = new Float32Array([
      0, 0, 0,   // start point
      100, 0, 0  // end point (100mm)
    ]);
    scaleGeometry.setAttribute('position', new THREE.BufferAttribute(scaleVertices, 3));
    
    const scaleMaterial = new THREE.LineBasicMaterial({ color: 0x88aacc, linewidth: 3 });
    const scaleLine = new THREE.Line(scaleGeometry, scaleMaterial);
    scaleLine.name = 'scaleLine';
    this.scaleGroup.add(scaleLine);

    // Tick marks at 0 and 100
    const tickGeometry = new THREE.BufferGeometry();
    const tickVertices = new Float32Array([
      // Tick at 0
      0, -5, 0,
      0, 5, 0,
      // Tick at 100
      100, -5, 0,
      100, 5, 0
    ]);
    tickGeometry.setAttribute('position', new THREE.BufferAttribute(tickVertices, 3));
    
    const tickMaterial = new THREE.LineBasicMaterial({ color: 0x88aacc });
    const tickLines = new THREE.LineSegments(tickGeometry, tickMaterial);
    tickLines.name = 'scaleTicks';
    this.scaleGroup.add(tickLines);

    // Text sprite for "100mm"
    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');
    if (context) {
      canvas.width = 128;
      canvas.height = 32;
      context.fillStyle = '#88aacc';
      context.font = '16px Arial';
      context.textAlign = 'center';
      context.fillText('100mm', 64, 20);
    }

    const texture = new THREE.CanvasTexture(canvas);
    const spriteMaterial = new THREE.SpriteMaterial({ map: texture });
    const sprite = new THREE.Sprite(spriteMaterial);
    sprite.position.set(50, 15, 0); // Middle of the scale bar, slightly above
    sprite.scale.set(40, 10, 1);
    sprite.name = 'scaleText';
    this.scaleGroup.add(sprite);

    this.updateGridPosition();
  }

  private updateGridPosition(): void {
    // Position grid at lowest bounding box z, or z=0 if no geometry
    const z = this.boundingBox.isEmpty() ? 0 : this.boundingBox.min.z;
    this.scaleGroup.position.z = z;
  }

  /**
   * Toggle grid and scale bar visibility.
   */
  toggleGrid(show?: boolean): void {
    this.showGrid = show !== undefined ? show : !this.showGrid;
    this.scaleGroup.visible = this.showGrid;
  }

  /**
   * Get current grid visibility state.
   */
  getGridVisibility(): boolean {
    return this.showGrid;
  }

  /**
   * Set lighting preset by name.
   */
  setLightingPreset(presetName: string): void {
    const preset = getPreset(presetName);
    if (!preset) {
      console.warn(`Unknown lighting preset: ${presetName}`);
      return;
    }

    // Remove existing lights
    for (const light of this.lights) {
      this.scene.remove(light);
    }
    this.lights = [];

    // Create new lights from preset
    this.lights = createLightsFromPreset(preset);
    for (const light of this.lights) {
      this.scene.add(light);
    }

    // Handle X-ray mode
    if (preset.xrayMode) {
      this.enableXrayMode();
    } else if (this.currentLightingPreset === 'xray') {
      this.disableXrayMode();
    }

    this.currentLightingPreset = presetName;
  }

  /**
   * Get current lighting preset name.
   */
  getCurrentLightingPreset(): string {
    return this.currentLightingPreset;
  }

  /**
   * Enable X-ray mode (translucent materials).
   */
  private enableXrayMode(): void {
    for (const mesh of this.meshes) {
      if (mesh.material && 'opacity' in mesh.material) {
        const material = mesh.material as THREE.MeshStandardMaterial;
        material.opacity = 0.6;
        material.transparent = true;
      }
    }
  }

  /**
   * Disable X-ray mode (restore original materials).
   */
  private disableXrayMode(): void {
    for (const mesh of this.meshes) {
      if (mesh.material && 'opacity' in mesh.material) {
        const material = mesh.material as THREE.MeshStandardMaterial;
        material.opacity = 1.0;
        material.transparent = false;
      }
    }
  }

  /**
   * Set render mode (solid, wireframe, solid+wireframe, normals).
   */
  setRenderMode(mode: string): void {
    // Restore from previous mode
    this.restoreFromRenderMode();

    this.currentRenderMode = mode;

    switch (mode) {
      case 'solid':
        // Default state, nothing to do
        break;

      case 'wireframe':
        for (const mesh of this.meshes) {
          if (mesh.material && 'wireframe' in mesh.material) {
            (mesh.material as THREE.MeshStandardMaterial).wireframe = true;
          }
        }
        break;

      case 'solid+wireframe':
        for (const mesh of this.meshes) {
          // Create wireframe overlay
          const wireframeGeometry = mesh.geometry.clone();
          const wireframeMaterial = new THREE.MeshBasicMaterial({
            color: 0xaaccee,
            wireframe: true,
            polygonOffset: true,
            polygonOffsetFactor: -1,
            polygonOffsetUnits: -1,
          });
          const wireframeMesh = new THREE.Mesh(wireframeGeometry, wireframeMaterial);
          wireframeMesh.position.copy(mesh.position);
          wireframeMesh.rotation.copy(mesh.rotation);
          wireframeMesh.scale.copy(mesh.scale);
          
          this.scene.add(wireframeMesh);
          this.wireframeMeshes.set(mesh, wireframeMesh);
        }
        break;

      case 'normals':
        for (const mesh of this.meshes) {
          // Save original material
          if (mesh.material) {
            this.originalMaterials.set(mesh, mesh.material);
            mesh.material = new THREE.MeshNormalMaterial();
          }
        }
        this.setNormalReference(true);
        break;
    }
  }

  /**
   * Get current render mode.
   */
  getCurrentRenderMode(): string {
    return this.currentRenderMode;
  }

  /**
   * Restore meshes from current render mode.
   */
  private restoreFromRenderMode(): void {
    switch (this.currentRenderMode) {
      case 'wireframe':
        for (const mesh of this.meshes) {
          if (mesh.material && 'wireframe' in mesh.material) {
            (mesh.material as THREE.MeshStandardMaterial).wireframe = false;
          }
        }
        break;

      case 'solid+wireframe':
        // Remove wireframe meshes
        for (const [, wireframeMesh] of this.wireframeMeshes) {
          this.scene.remove(wireframeMesh);
          wireframeMesh.geometry.dispose();
          if (wireframeMesh.material instanceof THREE.Material) {
            wireframeMesh.material.dispose();
          }
        }
        this.wireframeMeshes.clear();
        break;

      case 'normals':
        // Restore original materials
        for (const [mesh, originalMaterial] of this.originalMaterials) {
          if (mesh.material) {
            if (Array.isArray(mesh.material)) {
              mesh.material.forEach(mat => mat.dispose());
            } else {
              mesh.material.dispose();
            }
          }
          mesh.material = originalMaterial;
        }
        this.originalMaterials.clear();
        this.setNormalReference(false);
        break;
    }
  }

  /**
   * Set clipping plane for an axis.
   */
  /**
   * Set or remove a clipping plane for an axis.
   * Position is normalized 0-1 mapping to bounding box min→max.
   * 
   * THREE.Plane equation: normal · point + constant = 0
   * For clipping, points where normal · point + constant < 0 are clipped.
   * 
   * Non-inverted (keep geometry on the positive side of position):
   *   normal = -axis, constant = +worldPosition
   *   Clips everything below worldPosition on that axis.
   * 
   * Inverted (keep geometry on the negative side of position):
   *   normal = +axis, constant = -worldPosition
   *   Clips everything above worldPosition on that axis.
   */
  setClipPlane(axis: 'x' | 'y' | 'z', enabled: boolean, position: number, invert: boolean = false): void {
    if (!enabled) {
      this.clippingPlaneMap.delete(axis);
    } else {
      const axisIndex = { x: 0, y: 1, z: 2 }[axis];
      const min = this.boundingBox.min.getComponent(axisIndex);
      const max = this.boundingBox.max.getComponent(axisIndex);
      const worldPos = min + (max - min) * position;

      const normal = new THREE.Vector3();
      if (invert) {
        normal.setComponent(axisIndex, 1);
        this.clippingPlaneMap.set(axis, new THREE.Plane(normal, -worldPos));
      } else {
        normal.setComponent(axisIndex, -1);
        this.clippingPlaneMap.set(axis, new THREE.Plane(normal, worldPos));
      }
    }

    this.renderer.clippingPlanes = Array.from(this.clippingPlaneMap.values());
  }

  /**
   * Reset all clipping planes.
   */
  resetClipPlanes(): void {
    this.clippingPlaneMap.clear();
    this.renderer.clippingPlanes = [];
  }

  /**
   * Get current clipping planes state for UI sync.
   */
  getClippingState(): { axis: string; enabled: boolean; position: number; invert: boolean }[] {
    const axes: Array<'x' | 'y' | 'z'> = ['x', 'y', 'z'];
    return axes.map((axis) => {
      const plane = this.clippingPlaneMap.get(axis);
      if (!plane) {
        return { axis, enabled: false, position: 0.5, invert: false };
      }

      const axisIndex = { x: 0, y: 1, z: 2 }[axis];
      const invert = plane.normal.getComponent(axisIndex) > 0;
      const min = this.boundingBox.min.getComponent(axisIndex);
      const max = this.boundingBox.max.getComponent(axisIndex);
      const worldPos = invert ? -plane.constant : plane.constant;
      const position = max > min ? (worldPos - min) / (max - min) : 0.5;

      return { axis, enabled: true, position: Math.max(0, Math.min(1, position)), invert };
    });
  }

  /**
   * Load geometry entities into the scene.
   */
  loadGeometry(entities: GeometryEntity[]): void {
    // Clear existing meshes
    this.clearGeometry();

    for (const entity of entities) {
      const geometry = new THREE.BufferGeometry();

      // Position attribute
      geometry.setAttribute('position', new THREE.BufferAttribute(entity.vertices, 3));

      // Normal attribute
      if (entity.normals && entity.normals.length > 0) {
        geometry.setAttribute('normal', new THREE.BufferAttribute(entity.normals, 3));
      } else {
        geometry.computeVertexNormals();
      }

      // Index attribute
      if (entity.indices && entity.indices.length > 0) {
        geometry.setIndex(new THREE.BufferAttribute(entity.indices, 1));
      }

      // Material
      const materialName = entity.material || 'default';
      const material = this.materials.get(materialName) || this.materials.get('default')!;

      // Create mesh
      const mesh = new THREE.Mesh(geometry, material);
      mesh.name = entity.name || entity.id;
      mesh.userData = { entityId: entity.id, layer: entity.layer };

      this.scene.add(mesh);
      this.meshes.push(mesh);
    }

    // Calculate bounding box for clipping planes
    this.updateBoundingBox();

    // Update grid position based on new geometry
    this.updateGridPosition();

    // Apply current lighting preset effects
    const currentPreset = getPreset(this.currentLightingPreset);
    if (currentPreset?.xrayMode) {
      this.enableXrayMode();
    }

    // Apply current render mode
    if (this.currentRenderMode !== 'solid') {
      const mode = this.currentRenderMode;
      this.currentRenderMode = 'solid';
      this.setRenderMode(mode);
    }
  }

  /**
   * Clear all geometry from the scene.
   */
  clearGeometry(): void {
    // Restore from current render mode first
    this.restoreFromRenderMode();
    
    for (const mesh of this.meshes) {
      this.scene.remove(mesh);
      mesh.geometry.dispose();
    }
    this.meshes = [];
    
    // Clear render mode state
    this.originalMaterials.clear();
    this.wireframeMeshes.clear();
    
    // Reset bounding box
    this.boundingBox = new THREE.Box3();
  }

  /**
   * Update bounding box from current meshes.
   */
  private updateBoundingBox(): void {
    this.boundingBox = new THREE.Box3();
    for (const mesh of this.meshes) {
      this.boundingBox.expandByObject(mesh);
    }
  }

  /**
   * Fit camera to show all geometry with padding.
   */
  fitToGeometry(): void {
    const box = new THREE.Box3();

    for (const mesh of this.meshes) {
      box.expandByObject(mesh);
    }

    if (box.isEmpty()) return;

    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());

    if (this.isOrthographic) {
      const maxDim = Math.max(size.x, size.y, size.z);
      const frustumSize = maxDim * 1.5; // Add padding
      const aspect = this.options.container.clientWidth / this.options.container.clientHeight || 1;
      
      const ortho = this.camera as THREE.OrthographicCamera;
      ortho.left = (-frustumSize * aspect) / 2;
      ortho.right = (frustumSize * aspect) / 2;
      ortho.top = frustumSize / 2;
      ortho.bottom = -frustumSize / 2;
      ortho.near = -maxDim * 10;
      ortho.far = maxDim * 10;
      ortho.updateProjectionMatrix();
      
      // Preserve camera direction but re-center on geometry
      // Camera direction was set by setupViewCamera — keep it, just adjust distance and target
      const direction = new THREE.Vector3();
      this.camera.getWorldDirection(direction);
      const distance = maxDim * 3;
      this.camera.position.copy(center).sub(direction.multiplyScalar(distance));
    } else {
      const maxDim = Math.max(size.x, size.y, size.z);
      const fov = (this.camera as THREE.PerspectiveCamera).fov * (Math.PI / 180);
      let distance = Math.abs(maxDim / Math.tan(fov / 2));
      distance *= 1.5; // Add padding

      // Position camera at an angle
      this.camera.position.set(
        center.x + distance * 0.7,
        center.y + distance * 0.5,
        center.z + distance * 0.7
      );
    }

    this.controls.target.copy(center);
    this.controls.update();
  }

  /**
   * Start the render loop.
   */
  start(): void {
    if (this.renderId !== null) return;

    const animate = () => {
      this.renderId = requestAnimationFrame(animate);
      this.controls.update();
      this.renderer.render(this.scene, this.camera);
    };

    animate();
  }

  /**
   * Stop the render loop.
   */
  stop(): void {
    if (this.renderId !== null) {
      cancelAnimationFrame(this.renderId);
      this.renderId = null;
    }
  }

  private normalRefSphere: THREE.Mesh | null = null;

  /**
   * Add/remove a reference icosahedron for normals view.
   * Shows correct face orientation for comparison.
   */
  setNormalReference(show: boolean): void {
    if (show && !this.normalRefSphere) {
      const size = this.boundingBox.isEmpty() ? 10 : this.boundingBox.getSize(new THREE.Vector3()).length() * 0.12;
      const geo = new THREE.IcosahedronGeometry(size, 1);
      const mat = new THREE.MeshNormalMaterial();
      this.normalRefSphere = new THREE.Mesh(geo, mat);

      // Position in top-right corner of bounding box
      const max = this.boundingBox.isEmpty()
        ? new THREE.Vector3(20, 20, 20)
        : this.boundingBox.max.clone();
      const bsize = this.boundingBox.getSize(new THREE.Vector3());
      this.normalRefSphere.position.set(
        max.x + bsize.x * 0.3,
        max.y + bsize.y * 0.3,
        max.z
      );
      this.normalRefSphere.userData = { isNormalRef: true };
      this.scene.add(this.normalRefSphere);
    } else if (!show && this.normalRefSphere) {
      this.scene.remove(this.normalRefSphere);
      this.normalRefSphere.geometry.dispose();
      (this.normalRefSphere.material as THREE.Material).dispose();
      this.normalRefSphere = null;
    }
  }

  /**
   * Get unique layer names from loaded geometry.
   */
  getLayers(): string[] {
    const layers = new Set<string>();
    for (const mesh of this.meshes) {
      const layer = mesh.userData?.layer || 'default';
      layers.add(layer);
    }
    return Array.from(layers).sort();
  }

  /**
   * Set visibility of a specific layer.
   */
  setLayerVisibility(layer: string, visible: boolean): void {
    for (const mesh of this.meshes) {
      const meshLayer = mesh.userData?.layer || 'default';
      if (meshLayer === layer) {
        mesh.visible = visible;
        // Also update wireframe meshes if they exist
        const wireframe = this.wireframeMeshes.get(mesh);
        if (wireframe) {
          wireframe.visible = visible;
        }
      }
    }
  }

  /**
   * Get the Three.js scene for external manipulation.
   */
  getScene(): THREE.Scene {
    return this.scene;
  }

  /**
   * Get the camera for external manipulation.
   */
  getCamera(): THREE.Camera {
    return this.camera;
  }

  /**
   * Manual resize handler for external calls.
   */
  handleResize(): void {
    const { clientWidth, clientHeight } = this.options.container;
    if (clientWidth === 0 || clientHeight === 0) return;
    
    if (this.isOrthographic) {
      const aspect = clientWidth / clientHeight;
      const frustumSize = 200;
      (this.camera as THREE.OrthographicCamera).left = (-frustumSize * aspect) / 2;
      (this.camera as THREE.OrthographicCamera).right = (frustumSize * aspect) / 2;
      (this.camera as THREE.OrthographicCamera).top = frustumSize / 2;
      (this.camera as THREE.OrthographicCamera).bottom = -frustumSize / 2;
    } else {
      (this.camera as THREE.PerspectiveCamera).aspect = clientWidth / clientHeight;
    }
    
    (this.camera as THREE.PerspectiveCamera | THREE.OrthographicCamera).updateProjectionMatrix();
    this.renderer.setSize(clientWidth, clientHeight);
  }

  /**
   * Dispose of all resources.
   */
  dispose(): void {
    this.stop();
    this.clearGeometry();

    // Dispose materials
    for (const material of this.materials.values()) {
      material.dispose();
    }
    this.materials.clear();

    // Disconnect resize observer
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }

    // Dispose renderer
    this.renderer.dispose();

    // Remove DOM element
    this.options.container.removeChild(this.renderer.domElement);
  }
}

export default YapCADViewer;
