/**
 * YapCADViewer - Three.js-based 3D viewer for yapCAD geometry.
 * 
 * Generated by qwen3-coder:30b, reviewed and integrated by Jarvis.
 */

import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { createLightsFromPreset, getPreset } from './lighting';

export interface GeometryEntity {
  id: string;
  name?: string;
  vertices: Float32Array;
  normals?: Float32Array;
  indices?: Uint32Array;
  material?: string;
  layer?: string;
}

export interface ViewerOptions {
  container: HTMLElement;
  antialias?: boolean;
  pixelRatio?: number;
  orthographic?: boolean;
}

export interface Measurement {
  id: string;
  type: 'point-to-point';
  pointA: THREE.Vector3;
  pointB: THREE.Vector3;
  distance: number; // mm
}

export interface BoundingBoxInfo {
  width: number;   // X extent, mm
  height: number;  // Y extent, mm
  depth: number;   // Z extent, mm
  center: { x: number; y: number; z: number };
}

export type MeasureUnit = 'mm' | 'in';
export type MeasureChangeCallback = (measurements: Measurement[]) => void;

export interface BboxGizmoParam {
  name: string;
  widget: 'bbox_x' | 'bbox_y' | 'bbox_z';
  value: number;
}

export class YapCADViewer {
  private scene: THREE.Scene;
  private camera: THREE.Camera;
  private renderer: THREE.WebGLRenderer;
  private controls: OrbitControls;
  private isOrthographic: boolean;
  private renderId: number | null = null;
  private meshes: THREE.Mesh[] = [];
  private materials: Map<string, THREE.MeshStandardMaterial> = new Map();
  private lights: THREE.Light[] = [];
  private currentLightingPreset: string = 'studio';
  private currentRenderMode: string = 'solid';
  private originalMaterials: Map<THREE.Mesh, THREE.Material | THREE.Material[]> = new Map();
  private wireframeMeshes: Map<THREE.Mesh, THREE.Mesh> = new Map();
  private clippingPlaneMap: Map<string, THREE.Plane> = new Map(); // keyed by 'x','y','z'
  private boundingBox: THREE.Box3 = new THREE.Box3();
  private resizeObserver: ResizeObserver | null = null;
  private scaleGroup: THREE.Group = new THREE.Group();
  private showGrid: boolean = true;

  // --- Bbox gizmo state ---
  private gizmoGroup: THREE.Group = new THREE.Group();
  private gizmoHandles: THREE.Mesh[] = [];
  private onBboxDrag: ((name: string, value: number) => void) | null = null;
  private onBboxDragEnd: ((name: string, value: number) => void) | null = null;
  private gizmoDrag: {
    param: BboxGizmoParam;
    axisDir: THREE.Vector3;
    axisOrigin: THREE.Vector3;
    handleMesh: THREE.Mesh;
    coneMesh: THREE.Mesh;
    lineMesh: THREE.Line;
  } | null = null;
  private _boundGizmoDown: ((e: MouseEvent) => void) | null = null;
  private _boundGizmoMove: ((e: MouseEvent) => void) | null = null;
  private _boundGizmoUp: ((e: MouseEvent) => void) | null = null;

  // --- Measurement state ---
  private measureMode: boolean = false;
  private measureUnit: 'mm' | 'in' = 'mm';
  private measurements: Measurement[] = [];
  private measureGroup: THREE.Group = new THREE.Group();
  private pendingPoint: THREE.Vector3 | null = null;   // first click, waiting for second
  private pendingMarker: THREE.Mesh | null = null;
  private measureChangeCallback: MeasureChangeCallback | null = null;
  private _boundMeasureClick: ((e: MouseEvent) => void) | null = null;

  constructor(private options: ViewerOptions) {
    // Scene
    this.scene = new THREE.Scene();
    this.scene.background = new THREE.Color(0x1a1a2e);

    // Camera
    this.isOrthographic = options.orthographic ?? false;
    const width = options.container.clientWidth || 100;
    const height = options.container.clientHeight || 100;
    const aspect = width / height;
    
    if (this.isOrthographic) {
      const frustumSize = 200;
      this.camera = new THREE.OrthographicCamera(
        (-frustumSize * aspect) / 2, (frustumSize * aspect) / 2,
        frustumSize / 2, -frustumSize / 2,
        0.1, 10000
      );
      this.camera.position.set(0, 0, 100);
    } else {
      this.camera = new THREE.PerspectiveCamera(50, aspect, 0.1, 10000);
      this.camera.position.set(0, 0, 100);
    }

    // Renderer
    this.renderer = new THREE.WebGLRenderer({
      antialias: options.antialias ?? true,
    });
    this.renderer.setSize(options.container.clientWidth, options.container.clientHeight);
    this.renderer.setPixelRatio(options.pixelRatio ?? window.devicePixelRatio);
    this.renderer.localClippingEnabled = true;
    options.container.appendChild(this.renderer.domElement);

    // Controls
    this.controls = new OrbitControls(this.camera, this.renderer.domElement);
    this.controls.enableDamping = true;
    this.controls.dampingFactor = 0.05;

    // Setup
    this.setupLights();
    this.setupMaterialPresets();
    this.setupResizeHandler();
    this.createScaleGrid();
    this.scene.add(this.scaleGroup);
    this.scene.add(this.measureGroup);
    this.scene.add(this.gizmoGroup);
  }

  private setupLights(): void {
    // Initialize with studio lighting preset
    this.setLightingPreset('studio');
  }

  private setupMaterialPresets(): void {
    const presets: Record<string, { color: number; metalness: number; roughness: number }> = {
      brass: { color: 0xb5a642, metalness: 0.8, roughness: 0.3 },
      steel: { color: 0x8090a0, metalness: 0.9, roughness: 0.4 },
      aluminum: { color: 0xd0d5dd, metalness: 0.7, roughness: 0.5 },
      copper: { color: 0xb87333, metalness: 0.85, roughness: 0.35 },
      plastic_white: { color: 0xf0f0f0, metalness: 0.0, roughness: 0.6 },
      plastic_black: { color: 0x202020, metalness: 0.0, roughness: 0.6 },
      plastic_red: { color: 0xcc3333, metalness: 0.0, roughness: 0.6 },
      plastic_blue: { color: 0x3366cc, metalness: 0.0, roughness: 0.6 },
      plastic_green: { color: 0x33cc66, metalness: 0.0, roughness: 0.6 },
      default: { color: 0x99bbdd, metalness: 0.2, roughness: 0.4 },
    };

    for (const [name, props] of Object.entries(presets)) {
      this.materials.set(name, new THREE.MeshStandardMaterial({
        color: props.color,
        metalness: props.metalness,
        roughness: props.roughness,
        side: THREE.DoubleSide,
      }));
    }
  }

  private setupResizeHandler(): void {
    const onResize = () => {
      const { clientWidth, clientHeight } = this.options.container;
      if (clientWidth === 0 || clientHeight === 0) return;
      
      if (this.isOrthographic) {
        const aspect = clientWidth / clientHeight;
        const frustumSize = 200;
        (this.camera as THREE.OrthographicCamera).left = (-frustumSize * aspect) / 2;
        (this.camera as THREE.OrthographicCamera).right = (frustumSize * aspect) / 2;
        (this.camera as THREE.OrthographicCamera).top = frustumSize / 2;
        (this.camera as THREE.OrthographicCamera).bottom = -frustumSize / 2;
      } else {
        (this.camera as THREE.PerspectiveCamera).aspect = clientWidth / clientHeight;
      }
      
      (this.camera as THREE.PerspectiveCamera | THREE.OrthographicCamera).updateProjectionMatrix();
      this.renderer.setSize(clientWidth, clientHeight);
    };

    // Use ResizeObserver for container-level resize (panel drag, etc.)
    if (typeof ResizeObserver !== 'undefined') {
      this.resizeObserver = new ResizeObserver(onResize);
      this.resizeObserver.observe(this.options.container);
    }
    // Fallback to window resize
    window.addEventListener('resize', onResize);
  }

  private createScaleGrid(): void {
    // Clear existing grid
    this.scaleGroup.clear();

    // Grid helper (500mm size, 10 divisions = 50mm grid squares)
    const gridHelper = new THREE.GridHelper(500, 10, 0x444466, 0x333344);
    gridHelper.name = 'grid';
    this.scaleGroup.add(gridHelper);

    // Scale bar - 100mm line from origin to (100,0,0)
    const scaleGeometry = new THREE.BufferGeometry();
    const scaleVertices = new Float32Array([
      0, 0, 0,   // start point
      100, 0, 0  // end point (100mm)
    ]);
    scaleGeometry.setAttribute('position', new THREE.BufferAttribute(scaleVertices, 3));
    
    const scaleMaterial = new THREE.LineBasicMaterial({ color: 0x88aacc, linewidth: 3 });
    const scaleLine = new THREE.Line(scaleGeometry, scaleMaterial);
    scaleLine.name = 'scaleLine';
    this.scaleGroup.add(scaleLine);

    // Tick marks at 0 and 100
    const tickGeometry = new THREE.BufferGeometry();
    const tickVertices = new Float32Array([
      // Tick at 0
      0, -5, 0,
      0, 5, 0,
      // Tick at 100
      100, -5, 0,
      100, 5, 0
    ]);
    tickGeometry.setAttribute('position', new THREE.BufferAttribute(tickVertices, 3));
    
    const tickMaterial = new THREE.LineBasicMaterial({ color: 0x88aacc });
    const tickLines = new THREE.LineSegments(tickGeometry, tickMaterial);
    tickLines.name = 'scaleTicks';
    this.scaleGroup.add(tickLines);

    // Text sprite for "100mm"
    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');
    if (context) {
      canvas.width = 128;
      canvas.height = 32;
      context.fillStyle = '#88aacc';
      context.font = '16px Arial';
      context.textAlign = 'center';
      context.fillText('100mm', 64, 20);
    }

    const texture = new THREE.CanvasTexture(canvas);
    const spriteMaterial = new THREE.SpriteMaterial({ map: texture });
    const sprite = new THREE.Sprite(spriteMaterial);
    sprite.position.set(50, 15, 0); // Middle of the scale bar, slightly above
    sprite.scale.set(40, 10, 1);
    sprite.name = 'scaleText';
    this.scaleGroup.add(sprite);

    this.updateGridPosition();
  }

  private updateGridPosition(): void {
    // Position grid at lowest bounding box z, or z=0 if no geometry
    const z = this.boundingBox.isEmpty() ? 0 : this.boundingBox.min.z;
    this.scaleGroup.position.z = z;
  }

  /**
   * Toggle grid and scale bar visibility.
   */
  toggleGrid(show?: boolean): void {
    this.showGrid = show !== undefined ? show : !this.showGrid;
    this.scaleGroup.visible = this.showGrid;
  }

  /**
   * Get current grid visibility state.
   */
  getGridVisibility(): boolean {
    return this.showGrid;
  }

  /**
   * Set lighting preset by name.
   */
  setLightingPreset(presetName: string): void {
    const preset = getPreset(presetName);
    if (!preset) {
      console.warn(`Unknown lighting preset: ${presetName}`);
      return;
    }

    // Remove existing lights
    for (const light of this.lights) {
      this.scene.remove(light);
    }
    this.lights = [];

    // Create new lights from preset
    this.lights = createLightsFromPreset(preset);
    for (const light of this.lights) {
      this.scene.add(light);
    }

    // Handle X-ray mode
    if (preset.xrayMode) {
      this.enableXrayMode();
    } else if (this.currentLightingPreset === 'xray') {
      this.disableXrayMode();
    }

    this.currentLightingPreset = presetName;
  }

  /**
   * Get current lighting preset name.
   */
  getCurrentLightingPreset(): string {
    return this.currentLightingPreset;
  }

  /**
   * Enable X-ray mode (translucent materials).
   */
  private enableXrayMode(): void {
    for (const mesh of this.meshes) {
      if (mesh.material && 'opacity' in mesh.material) {
        const material = mesh.material as THREE.MeshStandardMaterial;
        material.opacity = 0.6;
        material.transparent = true;
      }
    }
  }

  /**
   * Disable X-ray mode (restore original materials).
   */
  private disableXrayMode(): void {
    for (const mesh of this.meshes) {
      if (mesh.material && 'opacity' in mesh.material) {
        const material = mesh.material as THREE.MeshStandardMaterial;
        material.opacity = 1.0;
        material.transparent = false;
      }
    }
  }

  /**
   * Set render mode (solid, wireframe, solid+wireframe, normals).
   */
  setRenderMode(mode: string): void {
    // Restore from previous mode
    this.restoreFromRenderMode();

    this.currentRenderMode = mode;

    switch (mode) {
      case 'solid':
        // Default state, nothing to do
        break;

      case 'wireframe':
        for (const mesh of this.meshes) {
          if (mesh.material && 'wireframe' in mesh.material) {
            (mesh.material as THREE.MeshStandardMaterial).wireframe = true;
          }
        }
        break;

      case 'solid+wireframe':
        for (const mesh of this.meshes) {
          // Create wireframe overlay
          const wireframeGeometry = mesh.geometry.clone();
          const wireframeMaterial = new THREE.MeshBasicMaterial({
            color: 0xaaccee,
            wireframe: true,
            polygonOffset: true,
            polygonOffsetFactor: -1,
            polygonOffsetUnits: -1,
          });
          const wireframeMesh = new THREE.Mesh(wireframeGeometry, wireframeMaterial);
          wireframeMesh.position.copy(mesh.position);
          wireframeMesh.rotation.copy(mesh.rotation);
          wireframeMesh.scale.copy(mesh.scale);
          
          this.scene.add(wireframeMesh);
          this.wireframeMeshes.set(mesh, wireframeMesh);
        }
        break;

      case 'normals':
        for (const mesh of this.meshes) {
          // Save original material
          if (mesh.material) {
            this.originalMaterials.set(mesh, mesh.material);
            mesh.material = new THREE.MeshNormalMaterial();
          }
        }
        this.setNormalReference(true);
        break;
    }
  }

  /**
   * Get current render mode.
   */
  getCurrentRenderMode(): string {
    return this.currentRenderMode;
  }

  /**
   * Restore meshes from current render mode.
   */
  private restoreFromRenderMode(): void {
    switch (this.currentRenderMode) {
      case 'wireframe':
        for (const mesh of this.meshes) {
          if (mesh.material && 'wireframe' in mesh.material) {
            (mesh.material as THREE.MeshStandardMaterial).wireframe = false;
          }
        }
        break;

      case 'solid+wireframe':
        // Remove wireframe meshes
        for (const [, wireframeMesh] of this.wireframeMeshes) {
          this.scene.remove(wireframeMesh);
          wireframeMesh.geometry.dispose();
          if (wireframeMesh.material instanceof THREE.Material) {
            wireframeMesh.material.dispose();
          }
        }
        this.wireframeMeshes.clear();
        break;

      case 'normals':
        // Restore original materials
        for (const [mesh, originalMaterial] of this.originalMaterials) {
          if (mesh.material) {
            if (Array.isArray(mesh.material)) {
              mesh.material.forEach(mat => mat.dispose());
            } else {
              mesh.material.dispose();
            }
          }
          mesh.material = originalMaterial;
        }
        this.originalMaterials.clear();
        this.setNormalReference(false);
        break;
    }
  }

  /**
   * Set clipping plane for an axis.
   */
  /**
   * Set or remove a clipping plane for an axis.
   * Position is normalized 0-1 mapping to bounding box min→max.
   * 
   * THREE.Plane equation: normal · point + constant = 0
   * For clipping, points where normal · point + constant < 0 are clipped.
   * 
   * Non-inverted (keep geometry on the positive side of position):
   *   normal = -axis, constant = +worldPosition
   *   Clips everything below worldPosition on that axis.
   * 
   * Inverted (keep geometry on the negative side of position):
   *   normal = +axis, constant = -worldPosition
   *   Clips everything above worldPosition on that axis.
   */
  setClipPlane(axis: 'x' | 'y' | 'z', enabled: boolean, position: number, invert: boolean = false): void {
    if (!enabled) {
      this.clippingPlaneMap.delete(axis);
    } else {
      const axisIndex = { x: 0, y: 1, z: 2 }[axis];
      const min = this.boundingBox.min.getComponent(axisIndex);
      const max = this.boundingBox.max.getComponent(axisIndex);
      const worldPos = min + (max - min) * position;

      const normal = new THREE.Vector3();
      if (invert) {
        normal.setComponent(axisIndex, 1);
        this.clippingPlaneMap.set(axis, new THREE.Plane(normal, -worldPos));
      } else {
        normal.setComponent(axisIndex, -1);
        this.clippingPlaneMap.set(axis, new THREE.Plane(normal, worldPos));
      }
    }

    this.renderer.clippingPlanes = Array.from(this.clippingPlaneMap.values());
  }

  /**
   * Reset all clipping planes.
   */
  resetClipPlanes(): void {
    this.clippingPlaneMap.clear();
    this.renderer.clippingPlanes = [];
  }

  /**
   * Get current clipping planes state for UI sync.
   */
  getClippingState(): { axis: string; enabled: boolean; position: number; invert: boolean }[] {
    const axes: Array<'x' | 'y' | 'z'> = ['x', 'y', 'z'];
    return axes.map((axis) => {
      const plane = this.clippingPlaneMap.get(axis);
      if (!plane) {
        return { axis, enabled: false, position: 0.5, invert: false };
      }

      const axisIndex = { x: 0, y: 1, z: 2 }[axis];
      const invert = plane.normal.getComponent(axisIndex) > 0;
      const min = this.boundingBox.min.getComponent(axisIndex);
      const max = this.boundingBox.max.getComponent(axisIndex);
      const worldPos = invert ? -plane.constant : plane.constant;
      const position = max > min ? (worldPos - min) / (max - min) : 0.5;

      return { axis, enabled: true, position: Math.max(0, Math.min(1, position)), invert };
    });
  }

  /**
   * Load geometry entities into the scene.
   */
  loadGeometry(entities: GeometryEntity[]): void {
    // Clear existing meshes
    this.clearGeometry();

    for (const entity of entities) {
      const geometry = new THREE.BufferGeometry();

      // Position attribute
      geometry.setAttribute('position', new THREE.BufferAttribute(entity.vertices, 3));

      // Normal attribute
      if (entity.normals && entity.normals.length > 0) {
        geometry.setAttribute('normal', new THREE.BufferAttribute(entity.normals, 3));
      } else {
        geometry.computeVertexNormals();
      }

      // Index attribute
      if (entity.indices && entity.indices.length > 0) {
        geometry.setIndex(new THREE.BufferAttribute(entity.indices, 1));
      }

      // Material
      const materialName = entity.material || 'default';
      const material = this.materials.get(materialName) || this.materials.get('default')!;

      // Create mesh
      const mesh = new THREE.Mesh(geometry, material);
      mesh.name = entity.name || entity.id;
      mesh.userData = { entityId: entity.id, layer: entity.layer };

      this.scene.add(mesh);
      this.meshes.push(mesh);
    }

    // Calculate bounding box for clipping planes
    this.updateBoundingBox();

    // Update grid position based on new geometry
    this.updateGridPosition();

    // Apply current lighting preset effects
    const currentPreset = getPreset(this.currentLightingPreset);
    if (currentPreset?.xrayMode) {
      this.enableXrayMode();
    }

    // Apply current render mode
    if (this.currentRenderMode !== 'solid') {
      const mode = this.currentRenderMode;
      this.currentRenderMode = 'solid';
      this.setRenderMode(mode);
    }
  }

  /**
   * Clear all geometry from the scene.
   */
  clearGeometry(): void {
    // Restore from current render mode first
    this.restoreFromRenderMode();
    
    for (const mesh of this.meshes) {
      this.scene.remove(mesh);
      mesh.geometry.dispose();
    }
    this.meshes = [];
    
    // Clear render mode state
    this.originalMaterials.clear();
    this.wireframeMeshes.clear();
    
    // Reset bounding box
    this.boundingBox = new THREE.Box3();
  }

  /**
   * Update bounding box from current meshes.
   */
  private updateBoundingBox(): void {
    this.boundingBox = new THREE.Box3();
    for (const mesh of this.meshes) {
      this.boundingBox.expandByObject(mesh);
    }
  }

  /**
   * Fit camera to show all geometry with padding.
   */
  fitToGeometry(): void {
    const box = new THREE.Box3();

    for (const mesh of this.meshes) {
      box.expandByObject(mesh);
    }

    if (box.isEmpty()) return;

    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());

    if (this.isOrthographic) {
      const maxDim = Math.max(size.x, size.y, size.z);
      const frustumSize = maxDim * 1.5; // Add padding
      const aspect = this.options.container.clientWidth / this.options.container.clientHeight || 1;
      
      const ortho = this.camera as THREE.OrthographicCamera;
      ortho.left = (-frustumSize * aspect) / 2;
      ortho.right = (frustumSize * aspect) / 2;
      ortho.top = frustumSize / 2;
      ortho.bottom = -frustumSize / 2;
      ortho.near = -maxDim * 10;
      ortho.far = maxDim * 10;
      ortho.updateProjectionMatrix();
      
      // Preserve camera direction but re-center on geometry
      // Camera direction was set by setupViewCamera — keep it, just adjust distance and target
      const direction = new THREE.Vector3();
      this.camera.getWorldDirection(direction);
      const distance = maxDim * 3;
      this.camera.position.copy(center).sub(direction.multiplyScalar(distance));
    } else {
      const maxDim = Math.max(size.x, size.y, size.z);
      const fov = (this.camera as THREE.PerspectiveCamera).fov * (Math.PI / 180);
      let distance = Math.abs(maxDim / Math.tan(fov / 2));
      distance *= 1.5; // Add padding

      // Position camera at an angle
      this.camera.position.set(
        center.x + distance * 0.7,
        center.y + distance * 0.5,
        center.z + distance * 0.7
      );
    }

    this.controls.target.copy(center);
    this.controls.update();
  }

  /**
   * Start the render loop.
   */
  start(): void {
    if (this.renderId !== null) return;

    const animate = () => {
      this.renderId = requestAnimationFrame(animate);
      this.controls.update();
      this.renderer.render(this.scene, this.camera);
    };

    animate();
  }

  /**
   * Stop the render loop.
   */
  stop(): void {
    if (this.renderId !== null) {
      cancelAnimationFrame(this.renderId);
      this.renderId = null;
    }
  }

  private normalRefSphere: THREE.Mesh | null = null;

  /**
   * Add/remove a reference icosahedron for normals view.
   * Shows correct face orientation for comparison.
   */
  setNormalReference(show: boolean): void {
    if (show && !this.normalRefSphere) {
      const size = this.boundingBox.isEmpty() ? 10 : this.boundingBox.getSize(new THREE.Vector3()).length() * 0.12;
      const geo = new THREE.IcosahedronGeometry(size, 1);
      const mat = new THREE.MeshNormalMaterial();
      this.normalRefSphere = new THREE.Mesh(geo, mat);

      // Position in top-right corner of bounding box
      const max = this.boundingBox.isEmpty()
        ? new THREE.Vector3(20, 20, 20)
        : this.boundingBox.max.clone();
      const bsize = this.boundingBox.getSize(new THREE.Vector3());
      this.normalRefSphere.position.set(
        max.x + bsize.x * 0.3,
        max.y + bsize.y * 0.3,
        max.z
      );
      this.normalRefSphere.userData = { isNormalRef: true };
      this.scene.add(this.normalRefSphere);
    } else if (!show && this.normalRefSphere) {
      this.scene.remove(this.normalRefSphere);
      this.normalRefSphere.geometry.dispose();
      (this.normalRefSphere.material as THREE.Material).dispose();
      this.normalRefSphere = null;
    }
  }

  /**
   * Get unique layer names from loaded geometry.
   */
  getLayers(): string[] {
    const layers = new Set<string>();
    for (const mesh of this.meshes) {
      const layer = mesh.userData?.layer || 'default';
      layers.add(layer);
    }
    return Array.from(layers).sort();
  }

  /**
   * Set visibility of a specific layer.
   */
  setLayerVisibility(layer: string, visible: boolean): void {
    for (const mesh of this.meshes) {
      const meshLayer = mesh.userData?.layer || 'default';
      if (meshLayer === layer) {
        mesh.visible = visible;
        // Also update wireframe meshes if they exist
        const wireframe = this.wireframeMeshes.get(mesh);
        if (wireframe) {
          wireframe.visible = visible;
        }
      }
    }
  }

  /**
   * Get the Three.js scene for external manipulation.
   */
  getScene(): THREE.Scene {
    return this.scene;
  }

  /**
   * Get the camera for external manipulation.
   */
  getCamera(): THREE.Camera {
    return this.camera;
  }

  /**
   * Manual resize handler for external calls.
   */
  handleResize(): void {
    const { clientWidth, clientHeight } = this.options.container;
    if (clientWidth === 0 || clientHeight === 0) return;
    
    if (this.isOrthographic) {
      const aspect = clientWidth / clientHeight;
      const frustumSize = 200;
      (this.camera as THREE.OrthographicCamera).left = (-frustumSize * aspect) / 2;
      (this.camera as THREE.OrthographicCamera).right = (frustumSize * aspect) / 2;
      (this.camera as THREE.OrthographicCamera).top = frustumSize / 2;
      (this.camera as THREE.OrthographicCamera).bottom = -frustumSize / 2;
    } else {
      (this.camera as THREE.PerspectiveCamera).aspect = clientWidth / clientHeight;
    }
    
    (this.camera as THREE.PerspectiveCamera | THREE.OrthographicCamera).updateProjectionMatrix();
    this.renderer.setSize(clientWidth, clientHeight);
  }

  // ─────────────────────────────────────────────────────────────────
  //  MEASUREMENT API
  // ─────────────────────────────────────────────────────────────────

  /**
   * Enable or disable measurement mode.
   * In measure mode, mouse clicks raycast against mesh surfaces instead of
   * driving OrbitControls. Two clicks define a point-to-point measurement.
   */
  setMeasureMode(enabled: boolean): void {
    if (this.measureMode === enabled) return;
    this.measureMode = enabled;

    if (enabled) {
      // Disable orbit so clicks aren't consumed by camera drag
      this.controls.enabled = false;
      this.options.container.style.cursor = 'crosshair';

      this._boundMeasureClick = (e: MouseEvent) => this._onMeasureClick(e);
      this.renderer.domElement.addEventListener('click', this._boundMeasureClick);
    } else {
      this.controls.enabled = true;
      this.options.container.style.cursor = '';

      if (this._boundMeasureClick) {
        this.renderer.domElement.removeEventListener('click', this._boundMeasureClick);
        this._boundMeasureClick = null;
      }
      // Remove pending marker if the user left a first point dangling
      this._clearPendingPoint();
    }
  }

  getMeasureMode(): boolean {
    return this.measureMode;
  }

  /**
   * Register a callback invoked whenever the measurements list changes.
   */
  onMeasureChange(cb: MeasureChangeCallback): void {
    this.measureChangeCallback = cb;
  }

  /** Return a copy of the current measurements array. */
  getMeasurements(): Measurement[] {
    return [...this.measurements];
  }

  /** Delete a single measurement by id. */
  deleteMeasurement(id: string): void {
    const idx = this.measurements.findIndex(m => m.id === id);
    if (idx === -1) return;
    this.measurements.splice(idx, 1);
    this._rebuildMeasureGroup();
    this.measureChangeCallback?.(this.getMeasurements());
  }

  /** Delete all measurements. */
  clearMeasurements(): void {
    this.measurements = [];
    this._clearPendingPoint();
    this._rebuildMeasureGroup();
    this.measureChangeCallback?.(this.getMeasurements());
  }

  /**
   * Return bounding-box dimensions of all visible geometry, in mm.
   */
  getBoundingBoxInfo(): BoundingBoxInfo | null {
    if (this.boundingBox.isEmpty()) return null;
    const size = this.boundingBox.getSize(new THREE.Vector3());
    const center = this.boundingBox.getCenter(new THREE.Vector3());
    return {
      width: Math.round(size.x * 100) / 100,
      height: Math.round(size.y * 100) / 100,
      depth: Math.round(size.z * 100) / 100,
      center: {
        x: Math.round(center.x * 100) / 100,
        y: Math.round(center.y * 100) / 100,
        z: Math.round(center.z * 100) / 100,
      },
    };
  }

  /**
   * Format a raw mm distance for display in the current unit.
   */
  formatDist(mm: number): string {
    if (this.measureUnit === 'in') {
      return `${(mm / 25.4).toFixed(3)}"`;
    }
    return `${mm.toFixed(2)} mm`;
  }

  /**
   * Get current display unit.
   */
  getMeasureUnit(): 'mm' | 'in' {
    return this.measureUnit;
  }

  /**
   * Switch display unit and rebuild all measurement labels.
   */
  setMeasureUnit(unit: 'mm' | 'in'): void {
    if (this.measureUnit === unit) return;
    this.measureUnit = unit;
    this._rebuildMeasureGroup();
    this.measureChangeCallback?.(this.getMeasurements());
  }

  // ─── Private measurement helpers ────────────────────────────────

  private _onMeasureClick(e: MouseEvent): void {
    const rect = this.renderer.domElement.getBoundingClientRect();
    const ndc = new THREE.Vector2(
      ((e.clientX - rect.left) / rect.width) * 2 - 1,
      -((e.clientY - rect.top) / rect.height) * 2 + 1,
    );

    const raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(ndc, this.camera);

    // Only raycast against actual geometry meshes (not measurement overlays)
    const intersects = raycaster.intersectObjects(this.meshes, false);
    if (intersects.length === 0) return;

    const hit = intersects[0].point.clone();

    if (this.pendingPoint === null) {
      // First click — store point and show a marker
      this.pendingPoint = hit;
      this.pendingMarker = this._makePointMarker(hit, 0xffcc00);
      this.measureGroup.add(this.pendingMarker);
    } else {
      // Second click — create measurement
      const pointA = this.pendingPoint.clone();
      const pointB = hit;
      const distance = Math.round(pointA.distanceTo(pointB) * 100) / 100;

      const m: Measurement = {
        id: `m_${Date.now()}`,
        type: 'point-to-point',
        pointA,
        pointB,
        distance,
      };
      this.measurements.push(m);

      this._clearPendingPoint();
      this._addMeasurementVisuals(m);
      this.measureChangeCallback?.(this.getMeasurements());
    }
  }

  private _clearPendingPoint(): void {
    if (this.pendingMarker) {
      this.measureGroup.remove(this.pendingMarker);
      this.pendingMarker.geometry.dispose();
      (this.pendingMarker.material as THREE.Material).dispose();
      this.pendingMarker = null;
    }
    this.pendingPoint = null;
  }

  /**
   * Compute a reasonable world-unit size for measurement decorations,
   * proportional to the geometry's bounding-box diagonal.
   * Rule of thumb: markers ~0.5% of diagonal, labels ~3% of diagonal.
   */
  private _bbScale(): number {
    if (this.boundingBox.isEmpty()) return 10;
    return this.boundingBox.getSize(new THREE.Vector3()).length();
  }

  private _makePointMarker(pos: THREE.Vector3, color: number): THREE.Mesh {
    const r = Math.max(0.5, this._bbScale() * 0.005); // 0.5% of diagonal, min 0.5mm
    const geo = new THREE.SphereGeometry(r, 8, 6);
    const mat = new THREE.MeshBasicMaterial({ color, depthTest: false });
    const mesh = new THREE.Mesh(geo, mat);
    mesh.position.copy(pos);
    mesh.renderOrder = 999;
    return mesh;
  }

  private _makeLabelSprite(text: string, pos: THREE.Vector3): THREE.Sprite {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d')!;
    const fontSize = 28;
    const padding = 10;

    ctx.font = `bold ${fontSize}px Arial`;
    const textWidth = ctx.measureText(text).width;
    canvas.width = textWidth + padding * 2;
    canvas.height = fontSize + padding * 2;

    // Background
    ctx.fillStyle = 'rgba(20,20,40,0.88)';
    ctx.beginPath();
    ctx.roundRect(0, 0, canvas.width, canvas.height, 6);
    ctx.fill();

    // Text
    ctx.font = `bold ${fontSize}px Arial`;
    ctx.fillStyle = '#ffffff';
    ctx.textBaseline = 'middle';
    ctx.fillText(text, padding, canvas.height / 2);

    const texture = new THREE.CanvasTexture(canvas);
    const mat = new THREE.SpriteMaterial({ map: texture, depthTest: false });
    const sprite = new THREE.Sprite(mat);
    sprite.position.copy(pos);

    // Label height = 3% of bounding-box diagonal; width scales with canvas aspect ratio.
    // This keeps labels small enough to read without drowning the geometry.
    const labelH = Math.max(2, this._bbScale() * 0.03);
    const aspect = canvas.width / canvas.height;
    sprite.scale.set(labelH * aspect, labelH, 1);
    sprite.renderOrder = 1000;
    return sprite;
  }

  private _addMeasurementVisuals(m: Measurement): void {
    // Endpoint markers (white for finalised)
    const markerA = this._makePointMarker(m.pointA, 0x44aaff);
    const markerB = this._makePointMarker(m.pointB, 0x44aaff);
    markerA.userData.measureId = m.id;
    markerB.userData.measureId = m.id;
    this.measureGroup.add(markerA, markerB);

    // Dashed line between points
    const lineMat = new THREE.LineDashedMaterial({
      color: 0x44aaff,
      dashSize: 8,
      gapSize: 4,
      depthTest: false,
    });
    const lineGeo = new THREE.BufferGeometry().setFromPoints([m.pointA, m.pointB]);
    const line = new THREE.Line(lineGeo, lineMat);
    line.computeLineDistances();
    line.renderOrder = 998;
    line.userData.measureId = m.id;
    this.measureGroup.add(line);

    // Midpoint label — formatted in current unit
    const mid = m.pointA.clone().lerp(m.pointB, 0.5);
    const label = this._makeLabelSprite(this.formatDist(m.distance), mid);
    label.userData.measureId = m.id;
    this.measureGroup.add(label);
  }

  /** Rebuild all measurement visuals from scratch (used after deletion). */
  private _rebuildMeasureGroup(): void {
    // Remove all objects tagged with measureId (don't remove pending marker)
    const toRemove = this.measureGroup.children.filter(
      o => o.userData.measureId !== undefined
    );
    for (const obj of toRemove) {
      this.measureGroup.remove(obj);
      if ((obj as THREE.Mesh).geometry) (obj as THREE.Mesh).geometry.dispose();
      const mat = (obj as THREE.Mesh | THREE.Sprite).material;
      if (mat) {
        if (Array.isArray(mat)) mat.forEach(m => m.dispose());
        else (mat as THREE.Material).dispose();
      }
    }
    // Re-add visuals for remaining measurements
    for (const m of this.measurements) {
      this._addMeasurementVisuals(m);
    }
  }

  // ─────────────────────────────────────────────────────────────────
  //  BBOX GIZMO API
  // ─────────────────────────────────────────────────────────────────

  /**
   * Set interactive 3D dimension handles for bbox_ params.
   * Renders a line + cone + sphere handle for each axis param.
   * Dragging a handle calls onDrag live; mouseup calls onDragEnd to trigger re-eval.
   */
  setBboxGizmos(
    params: BboxGizmoParam[],
    onDrag: (name: string, value: number) => void,
    onDragEnd: (name: string, value: number) => void,
  ): void {
    this.clearBboxGizmos();
    if (params.length === 0) return;
    if (this.boundingBox.isEmpty()) return;

    this.onBboxDrag = onDrag;
    this.onBboxDragEnd = onDragEnd;

    const box = this.boundingBox;
    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());
    const handleRadius = Math.max(size.length() * 0.02, 1.5);

    const axisConfigs: Record<BboxGizmoParam['widget'], { dir: THREE.Vector3; axisIdx: number; color: number }> = {
      bbox_x: { dir: new THREE.Vector3(1, 0, 0), axisIdx: 0, color: 0xff4444 },
      bbox_y: { dir: new THREE.Vector3(0, 1, 0), axisIdx: 1, color: 0x44ff44 },
      bbox_z: { dir: new THREE.Vector3(0, 0, 1), axisIdx: 2, color: 0x4488ff },
    };

    for (const param of params) {
      const config = axisConfigs[param.widget];
      if (!config) continue;

      // Axis origin at bbox.min along this axis, center on other two
      const axisOrigin = center.clone();
      axisOrigin.setComponent(config.axisIdx, box.min.getComponent(config.axisIdx));

      // Handle position at bbox.max along this axis
      const handlePos = center.clone();
      handlePos.setComponent(config.axisIdx, box.max.getComponent(config.axisIdx));

      // Line from axis origin to handle
      const lineGeo = new THREE.BufferGeometry().setFromPoints([axisOrigin, handlePos]);
      const lineMat = new THREE.LineBasicMaterial({ color: config.color, depthTest: false, linewidth: 2 });
      const line = new THREE.Line(lineGeo, lineMat);
      line.renderOrder = 990;
      this.gizmoGroup.add(line);

      // Cone arrowhead at handle position, pointing along positive axis
      const coneLen = handleRadius * 4;
      const coneGeo = new THREE.ConeGeometry(handleRadius, coneLen, 8);
      const coneMat = new THREE.MeshBasicMaterial({ color: config.color, depthTest: false });
      const cone = new THREE.Mesh(coneGeo, coneMat);
      cone.position.copy(handlePos);
      // Rotate so cone points along the axis (default cone points +Y)
      if (param.widget === 'bbox_x') cone.rotation.z = -Math.PI / 2;
      else if (param.widget === 'bbox_z') cone.rotation.x = Math.PI / 2;
      // bbox_y: default orientation is correct
      cone.renderOrder = 990;
      this.gizmoGroup.add(cone);

      // Sphere drag handle
      const sphereGeo = new THREE.SphereGeometry(handleRadius * 1.8, 10, 7);
      const sphereMat = new THREE.MeshBasicMaterial({ color: config.color, depthTest: false });
      const sphere = new THREE.Mesh(sphereGeo, sphereMat);
      sphere.position.copy(handlePos);
      sphere.renderOrder = 991;
      sphere.userData = {
        gizmoParam: { ...param },
        axisDir: config.dir.clone(),
        axisOrigin: axisOrigin.clone(),
        lineMesh: line,
        coneMesh: cone,
      };
      this.gizmoGroup.add(sphere);
      this.gizmoHandles.push(sphere);
    }

    // Register mouse handlers
    this._boundGizmoDown = (e: MouseEvent) => this._onGizmoMouseDown(e);
    this._boundGizmoMove = (e: MouseEvent) => this._onGizmoMouseMove(e);
    this._boundGizmoUp = (e: MouseEvent) => this._onGizmoMouseUp(e);
    this.renderer.domElement.addEventListener('mousedown', this._boundGizmoDown);
    window.addEventListener('mousemove', this._boundGizmoMove);
    window.addEventListener('mouseup', this._boundGizmoUp);
  }

  /** Remove all bbox gizmos and event listeners. */
  clearBboxGizmos(): void {
    if (this._boundGizmoDown) {
      this.renderer.domElement.removeEventListener('mousedown', this._boundGizmoDown);
      this._boundGizmoDown = null;
    }
    if (this._boundGizmoMove) {
      window.removeEventListener('mousemove', this._boundGizmoMove);
      this._boundGizmoMove = null;
    }
    if (this._boundGizmoUp) {
      window.removeEventListener('mouseup', this._boundGizmoUp);
      this._boundGizmoUp = null;
    }

    for (const child of [...this.gizmoGroup.children]) {
      this.gizmoGroup.remove(child);
      if ((child as THREE.Mesh).geometry) (child as THREE.Mesh).geometry.dispose();
      const mat = (child as THREE.Mesh | THREE.Line).material;
      if (mat) {
        if (Array.isArray(mat)) mat.forEach(m => m.dispose());
        else (mat as THREE.Material).dispose();
      }
    }
    this.gizmoHandles = [];
    this.gizmoDrag = null;
    this.onBboxDrag = null;
    this.onBboxDragEnd = null;
  }

  private _getMouseNDC(e: MouseEvent): THREE.Vector2 {
    const rect = this.renderer.domElement.getBoundingClientRect();
    return new THREE.Vector2(
      ((e.clientX - rect.left) / rect.width) * 2 - 1,
      -((e.clientY - rect.top) / rect.height) * 2 + 1,
    );
  }

  /** Project mouse onto a camera-facing plane through axisOrigin, then onto the axis. */
  private _computeAxisValue(ndc: THREE.Vector2, axisOrigin: THREE.Vector3, axisDir: THREE.Vector3): number {
    const raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(ndc, this.camera);

    // Plane faces the camera, contains axisOrigin
    const camDir = new THREE.Vector3();
    this.camera.getWorldDirection(camDir);
    const plane = new THREE.Plane().setFromNormalAndCoplanarPoint(camDir, axisOrigin);

    const intersection = new THREE.Vector3();
    if (!raycaster.ray.intersectPlane(plane, intersection)) return 0;

    // Project onto axis
    return intersection.clone().sub(axisOrigin).dot(axisDir);
  }

  private _onGizmoMouseDown(e: MouseEvent): void {
    if (this.measureMode || this.gizmoHandles.length === 0) return;
    const ndc = this._getMouseNDC(e);
    const raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(ndc, this.camera);

    const hits = raycaster.intersectObjects(this.gizmoHandles, false);
    if (hits.length === 0) return;

    e.stopPropagation();
    const handle = hits[0].object as THREE.Mesh;
    const ud = handle.userData;

    this.controls.enabled = false;
    this.options.container.style.cursor = 'crosshair';

    this.gizmoDrag = {
      param: ud.gizmoParam as BboxGizmoParam,
      axisDir: ud.axisDir as THREE.Vector3,
      axisOrigin: ud.axisOrigin as THREE.Vector3,
      handleMesh: handle,
      coneMesh: ud.coneMesh as THREE.Mesh,
      lineMesh: ud.lineMesh as THREE.Line,
    };
  }

  private _onGizmoMouseMove(e: MouseEvent): void {
    if (!this.gizmoDrag) return;
    const { axisDir, axisOrigin, handleMesh, coneMesh, lineMesh, param } = this.gizmoDrag;

    const ndc = this._getMouseNDC(e);
    const newValue = Math.max(1, this._computeAxisValue(ndc, axisOrigin, axisDir));

    // Update handle + cone position
    const newPos = axisOrigin.clone().addScaledVector(axisDir, newValue);
    handleMesh.position.copy(newPos);
    coneMesh.position.copy(newPos);

    // Update line endpoint
    const positions = (lineMesh.geometry as THREE.BufferGeometry).getAttribute('position') as THREE.BufferAttribute;
    positions.setXYZ(1, newPos.x, newPos.y, newPos.z);
    positions.needsUpdate = true;
    lineMesh.geometry.computeBoundingSphere();

    this.onBboxDrag?.(param.name, newValue);
  }

  private _onGizmoMouseUp(e: MouseEvent): void {
    if (!this.gizmoDrag) return;
    const { axisDir, axisOrigin, param } = this.gizmoDrag;

    const ndc = this._getMouseNDC(e);
    const finalValue = Math.max(1, this._computeAxisValue(ndc, axisOrigin, axisDir));

    this.controls.enabled = true;
    this.options.container.style.cursor = '';
    this.gizmoDrag = null;

    this.onBboxDragEnd?.(param.name, finalValue);
  }

  /**
   * Dispose of all resources.
   */
  dispose(): void {
    this.stop();

    // Clean up gizmos
    this.clearBboxGizmos();
    this.scene.remove(this.gizmoGroup);

    // Clean up measurements
    if (this.measureMode) this.setMeasureMode(false);
    this.clearMeasurements();
    this.scene.remove(this.measureGroup);

    this.clearGeometry();

    // Dispose materials
    for (const material of this.materials.values()) {
      material.dispose();
    }
    this.materials.clear();

    // Disconnect resize observer
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }

    // Dispose renderer
    this.renderer.dispose();

    // Remove DOM element
    this.options.container.removeChild(this.renderer.domElement);
  }
}

export default YapCADViewer;
