/**
 * LayerPanel — layer visibility controls for the 3D viewer.
 * Generated by qwen3-coder:30b, reviewed and refined by Jarvis.
 */

// Layer visibility controls

interface LayerPanelProps {
  layers: string[];
  visibility: Record<string, boolean>;
  onToggle: (layer: string, visible: boolean) => void;
  onShowAll: () => void;
  onHideAll: () => void;
}

/** Generate deterministic colors for layers using golden angle rotation. */
function layerColor(index: number): string {
  const hue = (index * 137.508) % 360;
  return `hsl(${hue}, 70%, 60%)`;
}

export function LayerPanel({ layers, visibility, onToggle, onShowAll, onHideAll }: LayerPanelProps) {
  if (layers.length === 0) {
    return (
      <div style={{ padding: '16px', color: '#888', fontSize: '14px' }}>
        No layers found
      </div>
    );
  }

  return (
    <div style={{
      backgroundColor: '#1a1a2e',
      color: '#eee',
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      fontFamily: 'inherit',
    }}>
      {/* Header */}
      <div style={{
        padding: '12px 16px',
        borderBottom: '1px solid #333',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      }}>
        <span style={{ fontSize: '14px', fontWeight: 600 }}>Layers</span>
        <div style={{ display: 'flex', gap: '4px' }}>
          <button
            onClick={onShowAll}
            style={{
              background: '#333',
              color: '#eee',
              border: 'none',
              padding: '4px 8px',
              borderRadius: '3px',
              cursor: 'pointer',
              fontSize: '12px',
            }}
          >
            All
          </button>
          <button
            onClick={onHideAll}
            style={{
              background: '#333',
              color: '#eee',
              border: 'none',
              padding: '4px 8px',
              borderRadius: '3px',
              cursor: 'pointer',
              fontSize: '12px',
            }}
          >
            None
          </button>
        </div>
      </div>

      {/* Layer list */}
      <div style={{
        flex: 1,
        overflowY: 'auto',
      }}>
        {layers.map((layer, index) => {
          const visible = visibility[layer] !== false;
          return (
            <div
              key={layer}
              onClick={() => onToggle(layer, !visible)}
              style={{
                display: 'flex',
                alignItems: 'center',
                padding: '8px 16px',
                cursor: 'pointer',
                backgroundColor: visible ? '#252540' : '#1e1e30',
                borderBottom: '1px solid #1a1a2e',
                opacity: visible ? 1 : 0.5,
                transition: 'opacity 0.15s',
              }}
            >
              <div style={{
                width: '12px',
                height: '12px',
                borderRadius: '2px',
                backgroundColor: layerColor(index),
                marginRight: '10px',
                flexShrink: 0,
              }} />
              <span style={{
                flex: 1,
                fontSize: '13px',
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}>
                {layer}
              </span>
              <input
                type="checkbox"
                checked={visible}
                onChange={() => onToggle(layer, !visible)}
                onClick={(e) => e.stopPropagation()}
                style={{
                  width: '14px',
                  height: '14px',
                  cursor: 'pointer',
                  accentColor: '#3b82f6',
                }}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default LayerPanel;
